spring:
  application:
    name: FullProject

  # DataSource 配置
  datasource:
    url: jdbc:mysql://localhost:3306/campus_shop?useSSL=false&characterEncoding=UTF-8&rewriteBatchStatements=true 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wwt001129
    hikari:
      maximum-pool-size: 10

  # Redis最新配置 (Spring Boot 3.x)
  data:
    redis:
      host: localhost
      port: 6379
      password:      # 无密码则留空
      database: 0
      timeout: 3000ms
      connect-timeout: 5000ms
      client-name: foodmap-app
      # 连接池配置
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
          # MyBatis 配置

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.foodmap.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    root: info


mybatis-plus:
  type-aliases-package: com.foodmap.entity
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_null

ollama:
  api:
    endpoint:http://localhost:11434
  model: deepseek-r1:14b
  request:
    timeout: 60000

